"use client";
import { useCatalogCollection } from "@/hooks/useCatalogCollection";
import type { LocationItem } from "@/lib/catalog";
const fallback: LocationItem[] = [{id:"vavuniya",name:"Vavuniya",address:"No-256/4, Janushan Ice Cream, Kali Kovil Road, Nelukkulam, Vavuniya, Sri Lanka",phone:"024 222 6041",whatsapp:"077 601 5041",mapUrl:"",active:true,sortOrder:1}];
export default function FindJanushan(){
 const {items:locations,live}=useCatalogCollection<LocationItem>("locations",fallback); const loc=locations[0]||fallback[0];
 const maps=loc.mapUrl||`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(loc.address)}`; const embed=`https://www.google.com/maps?q=${encodeURIComponent(loc.address)}&output=embed`; const tel=loc.phone.replace(/\s/g,""); const orderPhone="94776015041";
 return <section className="find-world section" id="locations"><div className="find-head"><p className="section-kicker">CRAVING JIC?</p><h2>Find your next <em>scoop.</em></h2><p>{live?"Locations are managed live from the JIC Control Room.":"JIC is at Nelukkulam, Vavuniya. Call us to confirm availability before you visit."}</p></div><div className="find-layout"><article className="location-card"><span className="location-index">01 · JANUSHAN ICE CREAM</span><h3>{loc.name}</h3><p>{loc.address}</p><div className="location-actions"><a className="button button-primary" href={maps} target="_blank" rel="noreferrer">Get Directions ↗</a><a className="button button-ghost" href={`tel:${tel}`}>Call Us</a></div><div className="location-contact-grid"><a href={`tel:${tel}`}><small>PHONE</small><strong>{loc.phone}</strong></a><a href={`tel:+${orderPhone}`}><small>CALL TO ORDER</small><strong>+94 77 601 5041</strong></a></div></article><div className="map-shell"><iframe title="Janushan Ice Cream location map" src={embed} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><div className="map-badge"><span>JIC</span><strong>{loc.name.toUpperCase()}</strong></div></div></div></section>;
}
